name: IntelligentAntagonist
version: '${project.version}'
main: com.unipi.alexandris.minecraftplugin.intelligentantagonistplugin.IntelligentAntagonist
api-version: 1.20
authors: [ Antitonius ]
description: A whole unique non-playable character AI in a single plugin!
website: https://anthonyal.github.io
load: POSTWORLD
depend:
  - MythicMobs
  - ModelEngine
commands:
  intelligentantagonist:
    description: Command group for IntelligentAntagonist.
    aliases: ia
    permission: intelligentantagonist.admin
permissions:
  intelligentantagonist.admin:
    description: Access to all IntelligentAntagonist commands.
    default: op
